{% set name = "flake518" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake518-{{ version }}.tar.gz
  sha256: e02efcacb9609e4250265600c7efd559576ae75c93b8898e019fec63128c90b5

build:
  noarch: python
  entry_points:
    - flake518 = flake518.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<4
    - tomli >=0.10.2
    - flake8 >=3.0.0

test:
  imports:
    - flake518
  commands:
    - pip check
    - flake518 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/carstencodes/flake518
  summary: A small wrapper around flake8 to support PEP518 pyproject.toml as configuration file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
