{% set name = "flake518" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake518-{{ version }}.tar.gz
  sha256: 4345de7393fea6cf88ad601850b3aba722a0cf4023cbebaa6921218d7919ca53

build:
  noarch: python
  entry_points:
    - flake518 = flake518.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4
    - pdm-pep517
    - pip
  run:
    - python >=3.7,<4
    - tomli >=0.10.2
    - flake8 >=3.0.0

test:
  imports:
    - flake518
  commands:
    - pip check
    - flake518 --help
  requires:
    - pip

about:
  home: https://github.com/carstencodes/flake518
  summary: A small wrapper around flake8 to support PEP518 pyproject.toml as configuration file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
